#!/usr/bin/env bash
# CRANE — CRA Norm Engine installer
# Usage: curl -fsSL https://raw.githubusercontent.com/cra-norm-engine/crane/main/install.sh | bash

set -e

REPO_URL="https://github.com/cra-norm-engine/crane/archive/refs/heads/main.zip"
INSTALL_DIR="crane"

# ── Colours ──────────────────────────────────────────────────────────────────
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
RESET="\033[0m"

info()    { echo -e "${GREEN}[CRANE]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*"; exit 1; }

# ── Check prerequisites ───────────────────────────────────────────────────────
info "Checking prerequisites..."

if ! command -v docker &>/dev/null; then
    error "Docker is not installed. Install it from https://docs.docker.com/get-docker/ and re-run."
fi

if ! docker compose version &>/dev/null 2>&1; then
    error "Docker Compose is not available. Make sure you have Docker Desktop or the Compose plugin installed."
fi

if ! docker info &>/dev/null 2>&1; then
    error "Docker daemon is not running. Start Docker and re-run."
fi

# ── Download ─────────────────────────────────────────────────────────────────
info "Downloading CRANE..."

if [ -d "$INSTALL_DIR" ]; then
    warn "Directory '$INSTALL_DIR' already exists. Skipping download — using existing files."
else
    if command -v curl &>/dev/null; then
        curl -fsSL "$REPO_URL" -o /tmp/crane.zip
    elif command -v wget &>/dev/null; then
        wget -q "$REPO_URL" -O /tmp/crane.zip
    else
        error "Neither curl nor wget is installed. Install one and re-run."
    fi

    if command -v unzip &>/dev/null; then
        unzip -q /tmp/crane.zip -d /tmp/crane-extract
    else
        error "unzip is not installed. Install it (e.g. 'sudo apt install unzip') and re-run."
    fi

    mv /tmp/crane-extract/crane-main "$INSTALL_DIR"
    rm -rf /tmp/crane.zip /tmp/crane-extract
fi

cd "$INSTALL_DIR"

# ── Configure .env ────────────────────────────────────────────────────────────
if [ -f ".env" ]; then
    warn ".env already exists — skipping generation. Edit it manually if needed."
else
    info "Generating .env configuration..."

    # Generate a secure random secret key
    if command -v openssl &>/dev/null; then
        SECRET_KEY=$(openssl rand -hex 32)
    else
        SECRET_KEY=$(cat /dev/urandom | tr -dc 'a-f0-9' | head -c 64)
    fi

    # Generate a random postgres password
    if command -v openssl &>/dev/null; then
        POSTGRES_PASSWORD=$(openssl rand -hex 16)
    else
        POSTGRES_PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 32)
    fi

    cat > .env <<EOF
# Generated by CRANE installer on $(date)

# Database
POSTGRES_DB=cra_compliance
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PORT=5432

# Backend
BACKEND_HOST=0.0.0.0
BACKEND_PORT=8000
BACKEND_DEBUG=false
BACKEND_ENVIRONMENT=production
BACKEND_API_PREFIX=/api/v1
BACKEND_PROJECT_NAME=CRANE
BACKEND_SECRET_KEY=${SECRET_KEY}
BACKEND_ACCESS_TOKEN_EXPIRE_MINUTES=60
BACKEND_DATABASE_URL=postgresql+psycopg://postgres:${POSTGRES_PASSWORD}@postgres:5432/cra_compliance
BACKEND_CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
BACKEND_LOG_LEVEL=INFO

# Frontend
VITE_APP_NAME=CRANE
VITE_API_BASE_URL=http://localhost:8000/api/v1
VITE_REQUEST_TIMEOUT_MS=15000
EOF
    info ".env created with a generated secret key and database password."
fi

# ── Start ─────────────────────────────────────────────────────────────────────
info "Starting CRANE (this may take 3–5 minutes on first run)..."
docker compose up -d

# ── Wait for backend ──────────────────────────────────────────────────────────
info "Waiting for backend to be ready..."
MAX_WAIT=120
WAITED=0
until curl -sf http://localhost:8000/api/v1/health &>/dev/null; do
    if [ "$WAITED" -ge "$MAX_WAIT" ]; then
        warn "Backend did not respond in ${MAX_WAIT}s. Check logs: docker compose logs backend"
        break
    fi
    sleep 3
    WAITED=$((WAITED + 3))
done

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}  CRANE is ready!${RESET}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "  App:      ${GREEN}http://localhost:5173${RESET}"
echo -e "  API docs: ${GREEN}http://localhost:8000/docs${RESET}"
echo ""
echo -e "  Default login:"
echo -e "    Email:    ${YELLOW}admin@example.com${RESET}"
echo -e "    Password: ${YELLOW}admin1234${RESET}"
echo ""
echo -e "  You will be prompted to change the password on first login."
echo ""
echo -e "  To stop:    ${GREEN}docker compose down${RESET}"
echo -e "  To restart: ${GREEN}docker compose up -d${RESET}"
echo -e "  Logs:       ${GREEN}docker compose logs -f${RESET}"
echo ""
