# CRANE — CRA Norm Engine installer for Windows
# Usage: irm https://raw.githubusercontent.com/cra-norm-engine/crane/main/install.ps1 | iex

$ErrorActionPreference = "Stop"

$RepoUrl   = "https://github.com/cra-norm-engine/crane/archive/refs/heads/main.zip"
$InstallDir = "crane"
$ZipPath    = "$env:TEMP\crane.zip"
$ExtractDir = "$env:TEMP\crane-extract"

function Write-Info  { param($msg) Write-Host "[CRANE] $msg" -ForegroundColor Green }
function Write-Warn  { param($msg) Write-Host "[WARN]  $msg" -ForegroundColor Yellow }
function Write-Err   { param($msg) Write-Host "[ERROR] $msg" -ForegroundColor Red; exit 1 }

# ── Check prerequisites ───────────────────────────────────────────────────────
Write-Info "Checking prerequisites..."

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Err "Docker is not installed. Install Docker Desktop from https://docs.docker.com/get-docker/ and re-run."
}

try {
    docker compose version | Out-Null
} catch {
    Write-Err "Docker Compose is not available. Make sure Docker Desktop is installed and running."
}

try {
    docker info | Out-Null
} catch {
    Write-Err "Docker is not running. Start Docker Desktop and re-run."
}

# ── Download ──────────────────────────────────────────────────────────────────
Write-Info "Downloading CRANE..."

if (Test-Path $InstallDir) {
    Write-Warn "Directory '$InstallDir' already exists. Skipping download — using existing files."
} else {
    Invoke-WebRequest -Uri $RepoUrl -OutFile $ZipPath -UseBasicParsing
    Expand-Archive -Path $ZipPath -DestinationPath $ExtractDir -Force
    Move-Item "$ExtractDir\crane-main" $InstallDir
    Remove-Item $ZipPath, $ExtractDir -Recurse -Force
}

Set-Location $InstallDir

# ── Configure .env ────────────────────────────────────────────────────────────
if (Test-Path ".env") {
    Write-Warn ".env already exists — skipping generation. Edit it manually if needed."
} else {
    Write-Info "Generating .env configuration..."

    # Generate secure random values
    $bytes = New-Object byte[] 32
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $SecretKey = ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""

    $bytes2 = New-Object byte[] 16
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes2)
    $PgPassword = ($bytes2 | ForEach-Object { $_.ToString("x2") }) -join ""

    $envContent = @"
# Generated by CRANE installer on $(Get-Date -Format "yyyy-MM-dd HH:mm")

# Database
POSTGRES_DB=cra_compliance
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$PgPassword
POSTGRES_PORT=5432

# Backend
BACKEND_HOST=0.0.0.0
BACKEND_PORT=8000
BACKEND_DEBUG=false
BACKEND_ENVIRONMENT=production
BACKEND_API_PREFIX=/api/v1
BACKEND_PROJECT_NAME=CRANE
BACKEND_SECRET_KEY=$SecretKey
BACKEND_ACCESS_TOKEN_EXPIRE_MINUTES=60
BACKEND_DATABASE_URL=postgresql+psycopg://postgres:${PgPassword}@postgres:5432/cra_compliance
BACKEND_CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
BACKEND_LOG_LEVEL=INFO

# Frontend
VITE_APP_NAME=CRANE
VITE_API_BASE_URL=http://localhost:8000/api/v1
VITE_REQUEST_TIMEOUT_MS=15000
"@
    $envContent | Out-File -FilePath ".env" -Encoding utf8 -NoNewline
    Write-Info ".env created with generated secret key and database password."
}

# ── Start ─────────────────────────────────────────────────────────────────────
Write-Info "Starting CRANE (this may take 3-5 minutes on first run)..."
docker compose up -d

# ── Wait for backend ──────────────────────────────────────────────────────────
Write-Info "Waiting for backend to be ready..."
$maxWait = 120
$waited  = 0
while ($waited -lt $maxWait) {
    try {
        $resp = Invoke-WebRequest -Uri "http://localhost:8000/api/v1/health" -UseBasicParsing -TimeoutSec 2
        if ($resp.StatusCode -eq 200) { break }
    } catch {}
    Start-Sleep -Seconds 3
    $waited += 3
}

if ($waited -ge $maxWait) {
    Write-Warn "Backend did not respond in ${maxWait}s. Check logs: docker compose logs backend"
}

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host "  CRANE is ready!" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Green
Write-Host ""
Write-Host "  App:      " -NoNewline; Write-Host "http://localhost:5173" -ForegroundColor Green
Write-Host "  API docs: " -NoNewline; Write-Host "http://localhost:8000/docs" -ForegroundColor Green
Write-Host ""
Write-Host "  Default login:"
Write-Host "    Email:    " -NoNewline; Write-Host "admin@example.com" -ForegroundColor Yellow
Write-Host "    Password: " -NoNewline; Write-Host "admin1234" -ForegroundColor Yellow
Write-Host ""
Write-Host "  You will be prompted to change the password on first login."
Write-Host ""
Write-Host "  To stop:    " -NoNewline; Write-Host "docker compose down" -ForegroundColor Green
Write-Host "  To restart: " -NoNewline; Write-Host "docker compose up -d" -ForegroundColor Green
Write-Host "  Logs:       " -NoNewline; Write-Host "docker compose logs -f" -ForegroundColor Green
Write-Host ""
