<template>
  <AppButton v-if="enabled" variant="secondary" class="page-guide-trigger" :class="{ 'page-guide-trigger-embedded': ['compliance-journey', 'security-updates', 'lifecycle-notifications'].includes(String(route.name)) }" @click="start">
    <span aria-hidden="true">?</span> Guide
  </AppButton>
  <Teleport to="body">
    <div v-if="open" class="page-guide-layer" role="region" aria-labelledby="page-guide-title">
      <aside class="page-guide-card">
        <div class="page-guide-kicker">{{ pageTitle }} · {{ step + 1 }} / {{ steps.length }}</div>
        <h2 id="page-guide-title">{{ steps[step].title }}</h2>
        <p>{{ steps[step].text }}</p>
        <div class="page-guide-why"><strong>Why this matters:</strong> {{ steps[step].why }}</div>
        <div class="page-guide-progress" aria-hidden="true"><span v-for="(_, i) in steps" :key="i" :class="{ active: i === step, done: i < step }"></span></div>
        <div class="page-guide-actions">
          <button type="button" class="page-guide-secondary" @click="close">Skip tour</button>
          <button v-if="step > 0" type="button" class="page-guide-secondary" @click="back">Back</button>
          <button type="button" class="page-guide-primary" @click="next">{{ step === steps.length - 1 ? 'Finish' : 'Continue' }}</button>
        </div>
      </aside>
    </div>
  </Teleport>
  <Teleport to="body">
    <div v-if="hintOpen" class="guide-discovery" :style="hintStyle" role="dialog" aria-label="Guide tours available">
      <span class="guide-discovery-arrow" :style="hintArrowStyle" aria-hidden="true"></span>
      <div class="guide-discovery-kicker">NEW · INTERACTIVE HELP</div>
      <strong>Every page has its own guide</strong>
      <p>Select the <b>? Guide</b> button on any CRANE page to start a tour made specifically for that page. It highlights where to click, what to enter, and what to review.</p>
      <div class="guide-discovery-actions">
        <button type="button" class="page-guide-secondary" @click="hideHint">Got it</button>
        <button type="button" class="page-guide-primary" @click="openHintedGuide">Show me</button>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, ref, watch } from "vue";
import { useRoute } from "vue-router";
import AppButton from "@/components/AppButton.vue";

const route = useRoute();
const open = ref(false);
const step = ref(0);
const hintOpen = ref(false);
const hintStyle = ref<Record<string, string>>({});
const hintArrowStyle = ref<Record<string, string>>({});
let hintTarget: HTMLElement | null = null;
const excluded = new Set(["dashboard", "products", "product-detail", "release-gate", "my-tasks", "lifecycle-notifications", "security-updates", "release-report", "declarations", "risk-assessments", "risk-assessment-detail", "supplier-assurance", "third-party-component-detail", "annex-matrix", "certification-records", "support-hub", "audit-history", "sbom-records", "vulnerability-handling", "product-data", "settings", "maturity", "admin-users", "admin-ldap", "admin-roles", "login", "change-password", "not-found"]);
const pageCopy: Record<string, { title: string; intro: string; work: string; next: string }> = {
  "my-tasks": { title: "Task management", intro: "See work assigned to you, delegated work you track, and completed history.", work: "Use the board, filters, comments, assignments, and due dates to keep compliance work moving.", next: "Link tasks to a product, release, or Jira issue when work needs traceability." },
  "compliance-journey": { title: "Compliance journey", intro: "Follow the recommended CRA order for one product and release.", work: "Select a product and release, then open each phase to understand its evidence and next action.", next: "Use the linked action on each phase to jump to the exact workspace." },
  "release-report": { title: "Release compliance report", intro: "Review the consolidated evidence dossier for a release.", work: "Read product identity, risks, requirements, SBOM, vulnerabilities, support, declaration, and audit sections.", next: "Use the release workspace to correct gaps before exporting the report." },
  "declarations": { title: "Declarations of Conformity", intro: "Track Declaration of Conformity status across releases.", work: "Filter releases, inspect declaration state, and open the declaration workflow for a specific version.", next: "Keep the declaration aligned with the approved release evidence." },
  "release-declaration": { title: "Declaration of Conformity", intro: "Prepare the EU Declaration of Conformity for this release.", work: "Complete the declaration details, verify the covered product and version, and review the generated document.", next: "Only publish the declaration after the corresponding release gate is approved." },
  "security-updates": { title: "Security update history", intro: "Review security updates and their lifecycle status.", work: "Filter updates, inspect affected products and releases, and confirm communication and resolution details.", next: "Use product and release links to investigate overdue or incomplete updates." },
  "lifecycle-notifications": { title: "Lifecycle notifications", intro: "Monitor support-period and end-of-support notifications.", work: "Review pending, sent, and failed notifications and their recipient history.", next: "Correct support periods from the product or release workspace." },
  "risk-assessments": { title: "Risk assessments", intro: "Manage product and release cybersecurity risk assessments.", work: "Create, review, approve, archive, and filter assessments by product, release, framework, and status.", next: "Open an assessment to document threats, likelihood, impact, and treatments." },
  "risk-assessment-detail": { title: "Risk assessment", intro: "Work through one assessment and its risk items.", work: "Record threats, assets, likelihood, impact, mitigations, owners, and approval evidence.", next: "Approve only after residual risk and treatment decisions are documented." },
  "supplier-assurance": { title: "Supplier assurance", intro: "Coordinate third-party supplier and component assurance.", work: "Review suppliers, assessments, component traceability, and reassessment needs.", next: "Open a supplier or component to maintain evidence and follow-up tasks." },
  "supplier-assessment-detail": { title: "Supplier assessment", intro: "Complete assurance work for one supplier.", work: "Record scope, evidence, findings, status, and reassessment dates.", next: "Link supplier conclusions to affected components and releases." },
  "third-party-component-detail": { title: "Third-party component", intro: "Trace one external component through the product portfolio.", work: "Inspect versions, suppliers, SBOM appearances, criticality, and assessment status.", next: "Resolve missing assurance before approving affected releases." },
  "annex-matrix": { title: "CRA Annex I matrix", intro: "Map CRA essential requirements to products, releases, and evidence.", work: "Filter requirements, inspect mappings, and identify requirements without sufficient evidence.", next: "Open the linked product or release to attach and review evidence." },
  "certification-records": { title: "Certification records", intro: "Track external certifications and conformity records.", work: "Maintain scheme, scope, certificate dates, status, and supporting documents.", next: "Keep certification records synchronized with release and declaration decisions." },
  "support-hub": { title: "Support hub", intro: "Manage support commitments across products and releases.", work: "Find missing, expiring, and expired support periods and inspect notification readiness.", next: "Open the owning product or release to update the support commitment." },
  "changes": { title: "Substantial changes", intro: "Assess changes that may affect CRA conformity.", work: "Track change type, affected releases, substantiality criteria, assessment status, and required actions.", next: "Open a change to record the decision and downstream release work." },
  "change-detail": { title: "Change assessment", intro: "Evaluate one product or release change.", work: "Document the change, impacted versions, substantiality criteria, rationale, and required actions.", next: "Create or update release evidence when the change is substantial." },
  "audit-history": { title: "Audit history", intro: "Review the append-only CRANE audit trail.", work: "Filter events by actor, action, entity, and time to reconstruct important decisions.", next: "Use the linked entity to inspect the source record and its current state." },
  "sbom-records": { title: "SBOM records", intro: "Manage machine-readable software inventories.", work: "Inspect CycloneDX or SPDX records, quality findings, component counts, and release association.", next: "Compare SBOM changes and resolve quality gaps before release approval." },
  "vulnerability-handling": { title: "Vulnerability handling", intro: "Run the PSIRT workflow for product vulnerabilities.", work: "Triage CVEs, assess exploitability and EPSS, manage VEX decisions, remediation, and disclosure.", next: "Link resolved findings to the affected release and its evidence." },
  "product-data": { title: "Product data exchange", intro: "Export and import product compliance data.", work: "Choose a product or release scope, review the export contents, and validate imports before applying them.", next: "Keep an audit record of data exchanges and verify imported relationships." },
  settings: { title: "Settings", intro: "Configure CRANE for your organization and integrations.", work: "Review profile, permissions, notifications, Jira, LDAP, and other available administration settings.", next: "Change security-sensitive settings deliberately and verify the resulting connection." },
  maturity: { title: "Cybersecurity maturity", intro: "Assess organizational cybersecurity maturity across core domains.", work: "Answer the assessment questions, review domain scores, and identify evidence gaps.", next: "Use the results to prioritize improvements that support CRA readiness." },
  "admin-users": { title: "User administration", intro: "Manage CRANE users and their access.", work: "Invite, activate, deactivate, and review users and their assigned roles and permissions.", next: "Grant only the access required for each compliance responsibility." },
  "admin-ldap": { title: "LDAP administration", intro: "Configure directory authentication for CRANE.", work: "Set connection, search, mapping, and synchronization options, then test the configuration.", next: "Validate group-to-role mappings with a non-administrator account." },
  "admin-roles": { title: "Role administration", intro: "Control what users can do in CRANE.", work: "Review roles and permission groups and assign capabilities according to responsibility.", next: "Test a role with a representative user before broad assignment." },
};
const enabled = computed(() => !excluded.has(String(route.name)));
const pageTitle = computed(() => pageCopy[String(route.name)]?.title ?? "CRANE workspace");
const steps = computed(() => {
  const copy = pageCopy[String(route.name)] ?? { title: pageTitle.value, intro: "Understand the purpose of this CRANE workspace.", work: "Review the primary content, filters, forms, and actions on this page.", next: "Follow links to the related product, release, task, or administration workspace." };
  if (route.name === "compliance-journey") return [
    { target: '[data-guide="cj-selectors"]', title: "Choose product and release", text: "Select the product and exact release you are assessing. Both selectors define the scope of this journey.", why: "CRA evidence and decisions must be traceable to a specific product version." },
    { target: '[data-guide="cj-status"]', title: "Read readiness at a glance", text: "The completion count, donut, release status, and legend show how much of the journey is complete and where gaps remain.", why: "This is your high-level readiness signal before reviewing details." },
    { target: '[data-guide="cj-phases"]', title: "Follow the CRA phase order", text: "Use the phase rail to move through the journey in sequence. Completed phases are marked, and the current phase is emphasized.", why: "The order keeps product, risk, security, evidence, and release decisions connected." },
    { target: '[data-guide="cj-focus"]', title: "Understand the selected step", text: "The focus panel explains the step, its CRA reference, status, phase, and why it matters.", why: "A shared explanation prevents incomplete or inconsistent evidence." },
    { target: '[data-guide="cj-guidance"]', title: "Check requirements and FAQs", text: "Review the required inputs, practical guidance, and FAQs before taking action.", why: "These details turn the workflow into an actionable compliance checklist." },
    { target: '[data-guide="cj-action"]', title: "Open the work area", text: "Use the step action to jump to the exact CRANE page where the evidence or decision is recorded.", why: "Recording work in the linked workspace preserves end-to-end traceability." },
  ];
  if (route.name === "security-updates") return [
    { target: '[data-guide="security-header"]', title: "Select the affected release", text: "Search products, choose a product and release, then create or review an update.", why: "Security communications must identify affected versions." },
    { target: '[data-guide="security-history"]', title: "Review update history", text: "Open a row to inspect addressed CVEs, affected versions, distribution, and retention evidence.", why: "The history provides an auditable record of remediation." },
  ];
  if (route.name === "lifecycle-notifications") return [
    { target: '[data-guide="lifecycle-header"]', title: "Run the EOS analysis", text: "Run the check to refresh lifecycle alerts from current product support periods.", why: "Current support data drives reliable customer notifications." },
    { target: '[data-guide="lifecycle-filters"]', title: "Filter the alerts", text: "Search and filter by threshold, classification, EOS state, and sort order.", why: "Prioritising approaching or expired support focuses remediation." },
    { target: '[data-guide="lifecycle-summary"]', title: "Read the summary", text: "Use the summary cards to understand how many products have support and which need attention.", why: "A quick overview helps teams allocate follow-up work." },
    { target: '[data-guide="lifecycle-results"]', title: "Open affected products", text: "Review the detailed rows and follow links to update support commitments and notification readiness.", why: "The product record is the source of truth for lifecycle obligations." },
  ];
  if (route.name === "release-report") return [
    { target: '[data-guide="report-identity"]', title: "Confirm release identity", text: "Start with the product, version, manufacturer, generated status, and coverage meter.", why: "A report is only meaningful when its release scope is unambiguous." },
    { target: '[data-guide="report-risk"]', title: "Review risk assessment", text: "Check the documented cybersecurity risks, treatments, and remaining gaps.", why: "Risk decisions support the CRA security-by-design obligation." },
    { target: '[data-guide="report-sbom"]', title: "Verify the SBOM", text: "Review component counts, formats, and software inventory evidence for this release.", why: "The SBOM supports vulnerability response and supply-chain traceability." },
    { target: '[data-guide="report-conformity"]', title: "Check conformity evidence", text: "Inspect the assessment route, declarations, technical documentation, and support commitments.", why: "These records substantiate the conformity decision." },
    { target: '[data-guide="report-audit"]', title: "Confirm traceability", text: "Review modifications, reporting readiness, and recent audit activity before sign-off.", why: "Traceability makes the dossier defensible during review." },
    { target: '[data-guide="report-signoff"]', title: "Complete sign-off", text: "Use the sign-off section to confirm approval status and export the final report when ready.", why: "Approval should follow evidence review, not replace it." },
  ];
  if (route.name === "declarations") return [
    { target: '[data-guide="declarations-header"]', title: "Understand the declaration scope", text: "Declarations are maintained per product release under CRA Article 28.", why: "Each version needs its own accurate conformity statement." },
    { target: '[data-guide="declarations-list"]', title: "Open a release declaration", text: "Review product, version, DoC reference, status, and signatory, then open the row to prepare or download its declaration.", why: "The release record keeps the declaration linked to its evidence." },
  ];
  const custom: Record<string, string[][]> = {
    "risk-assessments": [["risk-header","Define assessment scope","Choose product, release, framework, and status.","A clear scope makes risk decisions reproducible."],["risk-filters","Filter the register","Find draft, review, approved, or archived assessments.","Focused review closes priority gaps."],["risk-list","Open an assessment","Document threats, likelihood, impact, mitigations, owners, and evidence.","The record is the source of truth for risk acceptance."]],
    "risk-assessment-detail": [["risk-detail-header","Confirm assessment context","Review product, release, framework, and status.","Conclusions must be tied to the correct release."],["risk-items","Document risk items","Record assets, threats, likelihood, impact, treatments, owners, and residual risk.","Structured data supports defensible decisions."],["risk-approval","Review and approve","Approve only after treatments and residual risk are documented.","Approval establishes accountability."]],
    "supplier-assurance": [["supplier-header","Start with supplier ownership","Add or select the supplier responsible for a third-party component or service.","CRA supply-chain decisions need a named supplier and internal owner."],["supplier-summary","Check the assurance overview","Review supplier, component, pending-review, and high-risk totals.","The overview shows where due-diligence work needs attention."],["supplier-register","Choose a supplier","Search the register and select one supplier to open its assurance workspace.","Supplier-specific records keep evidence and decisions traceable."],["supplier-identity","Verify supplier details","Check status, security contact, website, registration date, and ownership before assessing components.","Reliable contacts and ownership are essential for vulnerability coordination."],["supplier-tabs","Follow the due-diligence workflow","Use Components, Assessments, Products, Notifications, and Profile to review the complete supplier relationship.","These views connect supplied components to evidence, products, and maintainer communication."],["supplier-records","Maintain the active record","Add components, create assessments, connect SBOM matches, link releases, and record notifications in the selected tab.","Keeping these records current supports release approval and reassessment." ]],
    "supplier-assessment-detail": [["supplier-assessment-header","Confirm assessment scope","Review supplier, system version, tier, and status.","The assessment must identify exactly what was evaluated."],["supplier-responses","Record responses and findings","Document criteria decisions, rationale, severity, and mitigation plans.","Reasoned findings are auditable."],["supplier-evidence","Link evidence and decide","Attach evidence, review validity, and record approval or rejection.","Evidence supports release assurance."]],
    "third-party-component-detail": [["component-header","Confirm component identity","Verify the component, version, type, supplier, and support state.","Exact component identity is essential for supply-chain traceability."],["component-summary","Review exposure","Check how many releases, assessments, vulnerabilities, and maintainer notices are connected.","These totals reveal assurance and remediation gaps."],[".detail-grid > main > .card:nth-child(1)","Trace product usage","Review every product release using the component, including dependency type and criticality.","Affected releases define the scope of security action."],[".detail-grid > main > .card:nth-child(2)","Check due diligence","Open the supplier assessments that cover this component and verify reassessment status.","Current assurance supports release decisions."],[".detail-grid > main > .card:nth-child(3)","Review vulnerabilities","Inspect correlated findings, affected releases, severity, exploitation, and fixed versions.","Vulnerability handling must cover every affected release."],[".detail-grid > aside > .card:nth-child(1)","Verify identifiers and support","Maintain PURL, CPE, part number, support end, and update channel.","Machine-readable identifiers improve matching and lifecycle control."],[".detail-grid > aside > .card:nth-child(2)","Review maintainer coordination","Check notices sent to the supplier or maintainer and their status.","Documented coordination supports vulnerability remediation." ]],
    "annex-matrix": [["annex-header","Understand the requirement matrix","Use the matrix to assess CRA Annex I requirements for one product release.","Requirement coverage must be version-specific and evidence-based."],["annex-readiness","Review portfolio readiness","Use the readiness overview to identify products with incomplete requirement coverage.","Portfolio context helps prioritise compliance work."],["annex-scope","Select product and release","Choose the exact release whose requirements you want to assess.","Mappings and conclusions belong to a specific release."],["annex-matrix","Assess every requirement","Review status, rationale, risks, and evidence for each applicable requirement.","Complete mappings demonstrate how Annex I obligations are fulfilled." ]],
    "certification-records": [["cert-header","Filter certification scope","Filter by product and status to locate the relevant external conformity records.","Certificates must be connected to the correct product scope."],["cert-records","Review certification records","Check scheme, scope, validity, status, and supporting evidence, then open a row for details.","Current and verifiable certificates support the conformity route."],["cert-add","Add missing certification evidence","Create a record when a certificate or third-party assessment is not yet captured.","Centralised records prevent evidence gaps during release review." ]],
    "support-hub": [["support-header","Manage lifecycle operations","Refresh current data or export the EOS watch list for follow-up.","Support commitments drive CRA lifecycle obligations."],["support-summary","Read the fleet summary","Review tracked products, support gaps, approaching EOS, expired periods, and market actions.","The summary identifies urgent lifecycle work."],["support-eos","Prioritise end-of-support risk","Use the EOS watch list to find products needing updated commitments or customer communication.","Timely action reduces unsupported-product exposure."],["support-product","Inspect product support","Look up a product to review its support period and related lifecycle information.","The product record is the source of truth for support commitments."],["support-cve","Look up vulnerabilities","Search CVEs across supported products and releases.","Security support must account for known vulnerabilities."],["support-notifications","Track customer notifications","Review lifecycle and security communications and their delivery state.","Communication records provide evidence of customer notification."],["support-market","Manage recalls and withdrawals","Record market actions and their affected products, reasons, and status.","Market actions must remain traceable and coordinated." ]],
    "audit-history": [["audit-header","Understand the audit workspace","Use Audit History to reconstruct changes to products, releases, and managed users.","An append-only timeline supports accountability and evidence review."],["audit-filters","Choose the audited record","Select the entity type, exact instance, and number of rows to retrieve.","A precise scope keeps the timeline relevant and understandable."],["audit-timeline","Review the event timeline","Inspect actors, actions, timestamps, and changed data, then refresh when necessary.","The sequence shows who changed what and when." ]],
    "sbom-records": [["sbom-header","Choose product and release scope","Search and select a product or release before importing, uploading, or creating an SBOM record.","SBOM evidence must be tied to the exact product release."],["sbom-actions","Add or analyze an SBOM","Import a release artifact, upload a machine-readable SBOM for analysis, or create metadata manually.","Automated analysis provides stronger quality and vulnerability evidence."],["sbom-records","Review the SBOM register","Check format, specification version, component count, quality, generator, dates, and available actions.","The register identifies missing or outdated release inventories."],["sbom-readiness","Read the CRA readiness verdict","Open a record to review compliance status, required fixes, quality, components, and vulnerabilities.","The verdict turns raw SBOM data into actionable CRA checks."],["sbom-tabs","Inspect analysis details","Use Compliance, Quality, Diff, and Vulnerabilities to investigate findings and release-to-release changes.","Detailed analysis supports remediation before release approval." ]],
    "vulnerability-handling": [["psirt-header","Understand the PSIRT workspace","Use this workspace to coordinate vulnerability intake, remediation, disclosure, SBOM findings, and regulatory reporting.","A single workflow keeps vulnerability decisions and deadlines traceable."],["psirt-tabs","Navigate the PSIRT lifecycle","The tabs separate overview, policies, intake, remediation, advisories, SBOM records, and ENISA reporting.","Each stage has distinct evidence and ownership."],["psirt-overview","Review operational workload","Use the overview counts to identify new reports, overdue SLAs, embargoes, SBOMs, policies, and ENISA work.","The overview directs attention to urgent security work."],["psirt-art14","Understand CRA reporting clocks","Review the 24-hour, 72-hour, corrective-measure, and final-report milestones.","Active exploitation can trigger strict CRA Article 14 deadlines."],["psirt-tab-cvd-policies","Maintain CVD policies","Publish active coordinated vulnerability disclosure policies for affected products.","CRA requires accessible reporting and handling processes."],["psirt-tab-reports","Triage vulnerability intake","Assess reports, severity, priority, affected products, and evidence.","Consistent triage determines remediation and reporting urgency."],["psirt-tab-remediation","Track remediation","Assign fixes, due dates, affected releases, and resolution evidence.","Remediation must remain visible through closure."],["psirt-tab-advisories","Manage advisories","Prepare disclosure content, embargoes, publication status, and affected versions.","Clear advisories communicate fixes to users."],["psirt-tab-sbom","Connect SBOM findings","Review software inventories and findings feeding the vulnerability workflow.","SBOM correlation reveals affected components and releases."],["psirt-tab-enisa","Manage ENISA and CSIRT reporting","Track regulatory submissions, deadlines, comments, and final reports.","Reporting evidence demonstrates compliance with Article 14." ]],
    "product-data": [["data-header","Understand data exchange","Export or import complete CRANE product records using the versioned JSON format.","Portable records support migration, backup, and controlled exchange."],["data-export","Export a product","Select a product and download its releases, risks, policies, advisories, SBOMs, certifications, and related records.","A complete export preserves relationships and traceability."],["data-schema","Check the exchange format","Review or download the schema reference before integrating the export with another system.","Schema versioning prevents incompatible imports."],["data-import","Import a product safely","Choose a CRANE JSON export and review the parsed data before applying it.","Previewing prevents unintended or malformed records from being written."],["data-drop","Select the import file","Drop or browse for a JSON bundle within the supported size and schema constraints.","Validation at the boundary protects data integrity." ]],
    "settings": [["settings-header","Manage personal settings","Use Settings to control your account, appearance, preferences, security, and integrations.","Personal and integration settings affect how you access and use CRANE."],["settings-nav","Navigate settings","Use the section navigation to jump directly to a settings category.","Clear categories make configuration easier to review."],["settings-account","Maintain your profile","Review identity, access, and personal photo settings.","Accurate identity supports assignments and audit records."],["settings-appearance","Choose appearance","Set the interface theme and display preferences.","A readable interface improves daily use."],["settings-preferences","Configure preferences","Choose personal behavior and notification preferences.","Preferences keep CRANE aligned with your workflow."],["settings-security","Review account security","Manage password and security-related controls available to your account.","Secure accounts protect compliance evidence."],["settings-jira","Configure Jira Cloud","Connect Jira, choose defaults, map workflows, priorities, and assignees, then verify synchronization.","Correct mappings preserve task ownership and status across systems."],["settings-about","Review system information","Check the CRANE version and product information.","Version information helps with support and deployment checks." ]],
    "maturity": [["maturity-header","Manage maturity assessments","Create or open an ENISA SME cybersecurity maturity assessment.","Organisational maturity complements product-level CRA readiness."],["maturity-list","Select an assessment","Review existing assessments, scope, status, and creation date.","Versioned assessments show improvement over time."],["maturity-detail","Confirm assessment context","Review the title, scope, model, completion state, and review actions.","A defined scope makes maturity scores meaningful."],["maturity-metrics","Read maturity indicators","Check completion, overall score, profile, and evidence coverage.","These metrics distinguish answered questions from evidenced capability."],["maturity-tabs","Follow the assessment workflow","Move between Assessment, Improvement plan, and Results.","The workflow turns answers into prioritised actions."],["maturity-workspace","Answer and evidence questions","Work through domains, score each question, and connect relevant CRANE evidence.","Evidence-backed answers produce a defensible maturity result." ]],
    "admin-users": [["users-header","Manage user accounts","Invite users and understand that access changes take effect immediately.","Every compliance action should be attributable to an individual account."],["users-register","Find a user","Search and filter active, inactive, local, and LDAP-managed accounts.","The register is the starting point for access reviews."],["users-detail","Review user access","Inspect identity, status, authentication provider, roles, and direct permissions.","Access should match the user's compliance responsibilities."],["users-actions","Apply account changes","Update roles, permissions, activation, or other available account controls carefully.","Immediate changes can affect both access and task ownership." ]],
    "admin-ldap": [["ldap-header","Manage directory integration","Refresh LDAP status before testing or importing accounts.","Current connection status prevents misleading authentication results."],["ldap-status","Check connection status","Verify LDAP is enabled, reachable, and using the expected server and base DN.","Authentication depends on correct directory connectivity."],["ldap-test","Test credentials safely","Verify a representative account can bind without creating a local user.","A test confirms search and authentication configuration."],["ldap-import","Import directory users","Search LDAP, select initial roles, and import matching users into CRANE.","Imported users need appropriate least-privilege roles."],["ldap-config","Review configuration variables","Check the required environment variables and defaults used by the backend.","Configuration reference helps diagnose deployment problems." ]],
    "admin-roles": [["roles-header","Manage roles and permissions","Create roles and understand that access changes apply on the next request.","Roles provide consistent least-privilege access."],["roles-register","Select a role","Review system and custom roles and their permission counts.","The register exposes broad or incomplete access definitions."],["roles-detail","Review role purpose","Check the role description, type, and assigned permission total.","A clear purpose prevents accidental privilege expansion."],["roles-permissions","Configure grouped permissions","Grant only the capabilities needed for the role's responsibilities, then save deliberately.","Least privilege reduces security and compliance risk." ]],
  };
  if (custom[String(route.name)]) return custom[String(route.name)].map(([target,title,text,why]) => ({ target: target.startsWith(".") ? target : `[data-guide="${target}"]`, title, text, why }));
  return [
    { target: "h1", title: `Start with ${copy.title}`, text: copy.intro, why: "Knowing the page's purpose helps you make the next decision in the CRA workflow." },
    { target: ".card, .hub-card, .panel, section", title: "Review the main work area", text: copy.work, why: "The main content is where CRANE records or summarizes controlled compliance work." },
    { target: ".btn, button, a", title: "Use the available actions", text: copy.next, why: "Following the linked action preserves traceability between related CRANE records." },
  ];
});
function targetForStep(): HTMLElement | null { const selector = steps.value[step.value].target; return document.querySelector<HTMLElement>(selector.startsWith("[") ? `main ${selector}` : `main ${selector}`); }
function updateTarget(): void {
  document.querySelectorAll(".page-guide-target,.page-guide-section").forEach((el) => el.classList.remove("page-guide-target", "page-guide-section"));
  const el = targetForStep();
  if (!el) { if (step.value < steps.value.length - 1) { step.value++; nextTick(updateTarget); } else close(); return; }
  el.scrollIntoView({ behavior: "auto", block: "center" });
  el.classList.add("page-guide-target", "page-guide-section");
}
function start(): void { step.value = 0; open.value = true; document.body.classList.add("page-guide-open"); nextTick(updateTarget); }
function close(): void { document.querySelectorAll(".page-guide-target,.page-guide-section").forEach((el) => el.classList.remove("page-guide-target", "page-guide-section")); document.body.classList.remove("page-guide-open"); open.value = false; step.value = 0; }
function next(): void { if (step.value < steps.value.length - 1) { step.value++; nextTick(updateTarget); } else close(); }
function back(): void { if (step.value > 0) { step.value--; nextTick(updateTarget); } }
watch(() => route.name, close);
function onExternalStart(): void { if (["lifecycle-notifications", "security-updates", "release-report", "declarations", "risk-assessments", "risk-assessment-detail", "supplier-assurance", "third-party-component-detail", "annex-matrix", "certification-records", "support-hub", "audit-history", "sbom-records", "vulnerability-handling", "product-data", "settings", "maturity", "admin-users", "admin-ldap", "admin-roles"].includes(String(route.name))) start(); }
function hideHint(): void { hintOpen.value = false; hintTarget?.classList.remove("guide-hint-target"); hintTarget = null; }
function openHintedGuide(): void { const target = hintTarget; hideHint(); target?.click(); }
function showHint(): void {
  nextTick(() => requestAnimationFrame(() => {
    hintTarget = document.querySelector<HTMLElement>(".embedded-guide-trigger, .pi-guide-trigger, .pd-guide-trigger, .rg-guide-trigger, .dashboard-guide-trigger, .mt-guide-trigger, .page-guide-trigger");
    if (!hintTarget) return;
    const rect = hintTarget.getBoundingClientRect();
    const width = Math.min(310, window.innerWidth - 24);
    const left = Math.max(12, Math.min(rect.right - width, window.innerWidth - width - 12));
    const top = Math.min(rect.bottom + 18, window.innerHeight - 190);
    hintStyle.value = { width: `${width}px`, left: `${left}px`, top: `${top}px` };
    hintArrowStyle.value = { left: `${Math.max(20, Math.min(rect.left + rect.width / 2 - left - 8, width - 30))}px` };
    hintTarget.classList.add("guide-hint-target");
    hintTarget.addEventListener("click", hideHint, { once: true });
    hintOpen.value = true;
  }));
}
window.addEventListener("crane-guide-start", onExternalStart);
window.addEventListener("crane-guide-hint", showHint);
onBeforeUnmount(() => { hideHint(); window.removeEventListener("crane-guide-start", onExternalStart); window.removeEventListener("crane-guide-hint", showHint); document.body.classList.remove("page-guide-open"); });
</script>

<style scoped>
:global(body.page-guide-open .app-content) { padding-right: 390px; transition: padding-right .18s ease; }
.page-guide-trigger { position: fixed; top: 76px; right: 18px; z-index: 1100; }
.page-guide-trigger-embedded { position: absolute; top: 92px; right: 2rem; z-index: 1100; }
.page-guide-trigger :deep(span) { display: inline-grid; place-items: center; width: 16px; height: 16px; border: 1px solid currentColor; border-radius: 50%; font-size: 11px; font-weight: 700; }
.page-guide-layer { position: fixed; inset: 0; z-index: 1200; pointer-events: none; }
:global(.page-guide-section) { background: rgba(122, 204, 55, .10) !important; box-shadow: inset 4px 0 0 var(--color-primary) !important; }
:global(.page-guide-target) { outline: 2px solid var(--color-primary) !important; outline-offset: 5px !important; box-shadow: 0 0 0 4px rgba(120, 210, 50, .12) !important; border-radius: 4px; }
.page-guide-card { position: fixed; top: 76px; right: 18px; bottom: 18px; z-index: 1203; width: 340px; box-sizing: border-box; padding: 20px; overflow: auto; border: 1px solid var(--color-border); border-radius: 12px; background: var(--color-surface); color: var(--color-text); box-shadow: 0 8px 30px rgba(0,0,0,.2); pointer-events: auto; }
.page-guide-kicker { margin-bottom: 8px; color: var(--color-primary); font-size: 10px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
.page-guide-card h2 { margin: 0 0 8px; font-size: 18px; }
.page-guide-card p { margin: 0; color: var(--color-text-muted); font-size: 13px; line-height: 1.55; }
.page-guide-why { margin-top: 14px; padding: 11px 12px; border-left: 3px solid var(--color-primary); background: var(--color-surface-2); color: var(--color-text-muted); font-size: 12px; line-height: 1.5; }
.page-guide-progress { display: flex; gap: 4px; margin-top: 18px; }.page-guide-progress span { height: 3px; flex: 1; border-radius: 99px; background: var(--color-border); }.page-guide-progress span.active,.page-guide-progress span.done { background: var(--color-primary); }
.page-guide-actions { display: flex; justify-content: flex-end; gap: 8px; margin-top: 18px; }.page-guide-actions button { padding: 8px 11px; border-radius: 7px; font: inherit; cursor: pointer; }.page-guide-secondary { border: 1px solid var(--color-border); background: transparent; color: inherit; }.page-guide-primary { border: 1px solid var(--color-primary); background: var(--color-primary); color: #fff; }
:global(.guide-hint-target) { position: relative; z-index: 1302 !important; outline: 3px solid var(--color-primary) !important; outline-offset: 4px; animation: guide-hint-pulse 1.2s ease-in-out infinite; }
.guide-discovery { position: fixed; z-index: 1301; box-sizing: border-box; padding: 16px; border: 1px solid var(--color-primary); border-radius: 12px; background: var(--color-surface); color: var(--color-text); box-shadow: 0 14px 40px rgba(0,0,0,.32); }
.guide-discovery-arrow { position: absolute; top: -9px; width: 16px; height: 16px; border-top: 1px solid var(--color-primary); border-left: 1px solid var(--color-primary); background: var(--color-surface); transform: rotate(45deg); }
.guide-discovery-kicker { margin-bottom: 6px; color: var(--color-primary); font-size: 10px; font-weight: 800; letter-spacing: .08em; }
.guide-discovery > strong { display: block; font-size: var(--text-lg); }
.guide-discovery p { margin: 8px 0 14px; color: var(--color-text-muted); font-size: var(--text-sm); line-height: 1.5; }
.guide-discovery-actions { display: flex; justify-content: flex-end; gap: 8px; }
.guide-discovery-actions button { padding: 7px 10px; border-radius: 7px; font: inherit; cursor: pointer; }
@keyframes guide-hint-pulse { 50% { box-shadow: 0 0 0 8px rgba(122,204,55,.16); } }
@media (max-width: 1100px) { :global(body.page-guide-open .app-content) { padding-right: 2rem; }.page-guide-card { top: auto; left: 16px; right: 16px; bottom: 16px; width: auto; max-height: 42vh; }.page-guide-target { scroll-margin-bottom: 45vh; } }
</style>
