export type CraSourceId = "law" | "guidance" | "faq";
export type CraTopicId = "scope" | "roles" | "classification" | "security" | "vulnerability" | "reporting" | "conformity" | "market" | "timeline";

export interface CraReference { sourceId: CraSourceId; locator: string }
export interface CraLearningNode {
  id: string;
  title: string;
  shortLabel: string;
  kind: "concept" | "actor" | "obligation" | "process" | "deadline";
  topic: CraTopicId;
  summary: string;
  detail: string;
  references: CraReference[];
}
export interface CraLearningEdge { from: string; to: string; label: string; references: CraReference[] }

export const craSources = {
  law: { label: "CRA law", authority: "Binding EU regulation", url: "https://eur-lex.europa.eu/eli/reg/2024/2847/oj" },
  guidance: { label: "Commission guidance", authority: "Non-binding guidance", url: "https://digital-strategy.ec.europa.eu/en/library/commission-publishes-new-guidance-support-timely-cyber-resilience-act-implementation" },
  faq: { label: "Commission FAQ", authority: "Non-authoritative implementation aid", url: "https://digital-strategy.ec.europa.eu/en/library/cyber-resilience-act-implementation-frequently-asked-questions" },
} as const;

const r = (sourceId: CraSourceId, locator: string): CraReference => ({ sourceId, locator });
const law = (locator: string): CraReference[] => [r("law", locator)];
const n = (id: string, title: string, shortLabel: string, kind: CraLearningNode["kind"], topic: CraTopicId, summary: string, detail: string, references: CraReference[]): CraLearningNode => ({ id, title, shortLabel, kind, topic, summary, detail, references });
const e = (from: string, to: string, label: string, locator: string, sourceId: CraSourceId = "law"): CraLearningEdge => ({ from, to, label, references: [r(sourceId, locator)] });

export const craTopics: { id: CraTopicId | "all"; label: string }[] = [
  { id: "all", label: "All concepts" }, { id: "scope", label: "Scope & products" },
  { id: "roles", label: "Actors & roles" }, { id: "classification", label: "Classification" },
  { id: "security", label: "Product security" }, { id: "vulnerability", label: "Vulnerability handling" },
  { id: "reporting", label: "Reporting" }, { id: "conformity", label: "Conformity" },
  { id: "market", label: "Market oversight" }, { id: "timeline", label: "Timeline" },
];

export const craLearningNodes: CraLearningNode[] = [
  n("cra", "Cyber Resilience Act", "CRA", "concept", "scope", "Regulation (EU) 2024/2847 lays down horizontal cybersecurity requirements for products with digital elements.", "It establishes rules for placing products with digital elements on the Union market and requirements for their design, development, production and vulnerability handling.", law("Article 1")),
  n("pde", "Product with digital elements", "Digital product", "concept", "scope", "A software or hardware product and its remote data processing solutions, including software or hardware components placed on the market separately.", "Its intended purpose or reasonably foreseeable use includes a direct or indirect logical or physical data connection to a device or network.", law("Articles 2(1) and 3(1)")),
  n("software", "Software", "Software", "concept", "scope", "Software is part of the CRA definition of a product with digital elements.", "Software components placed on the market separately can also be products with digital elements.", law("Article 3(1), (5)")),
  n("hardware", "Hardware", "Hardware", "concept", "scope", "Hardware is part of the CRA definition of a product with digital elements.", "Hardware components placed on the market separately can also be products with digital elements.", law("Article 3(1), (6)")),
  n("component", "Software or hardware component", "Component", "concept", "scope", "A component can be software or hardware intended for integration into an electronic information system.", "A component placed on the market separately can fall within the product-with-digital-elements definition.", law("Article 3(1), (4)")),
  n("remote_processing", "Remote data processing solution", "Remote processing", "concept", "scope", "Remote data processing can be part of a product with digital elements when it is designed and developed by, or under the responsibility of, the manufacturer.", "The CRA definition covers remote processing whose absence would prevent the product from performing one of its functions.", [r("law", "Article 3(2)"), r("guidance", "Section 7")]),
  n("data_connection", "Logical or physical data connection", "Data connection", "concept", "scope", "The intended purpose or reasonably foreseeable use of an in-scope product includes a direct or indirect logical or physical data connection.", "The connection can be to a device or to a network.", law("Article 2(1)")),
  n("making_available", "Making available on the market", "Making available", "process", "scope", "Making available means supplying a product for distribution or use on the Union market in the course of a commercial activity.", "The supply can be in return for payment or free of charge.", law("Article 3")),
  n("placing_market", "Placing on the market", "Placing on market", "process", "scope", "Placing on the market is the first making available of a product with digital elements on the Union market.", "CRA manufacturer and conformity duties are tied to this market event.", law("Article 3")),
  n("commercial_activity", "Commercial activity", "Commercial activity", "concept", "scope", "The CRA market scope and the free-and-open-source exclusion use the concept of commercial activity.", "Commission guidance explains the assessment of commercial activity, including in the free and open-source context.", [r("law", "Article 2(1)"), r("guidance", "Sections 2 and 3")]),
  n("intended_use", "Intended purpose and foreseeable use", "Intended use", "concept", "scope", "CRA scope and risk assessment consider the manufacturer's intended purpose and reasonably foreseeable use.", "The Regulation defines both terms and uses them throughout product assessment.", law("Article 3")),
  n("foss", "Free and open-source software", "Free & open source", "concept", "scope", "Free and open-source software developed or supplied outside a commercial activity is outside the CRA's scope.", "The CRA defines qualifying free and open-source software and Commission guidance explains the commercial-activity boundary.", [r("law", "Articles 2(1) and 3(48)"), r("guidance", "Section 3")]),
  n("sector_exclusions", "Sector-specific exclusions", "Sector exclusions", "concept", "scope", "Article 2 excludes or specially treats specified products already governed by particular Union legislation.", "The listed areas include certain medical devices, motor vehicles, civil aviation products and marine equipment.", law("Article 2(2)-(5)")),

  n("economic_operator", "Economic operator", "Economic operator", "actor", "roles", "The CRA uses economic operator as an umbrella concept for specified actors in the supply chain.", "It includes the manufacturer, authorised representative, importer, distributor and other actors identified by the Regulation.", law("Article 3")),
  n("manufacturer", "Manufacturer", "Manufacturer", "actor", "roles", "A manufacturer develops or manufactures products with digital elements, or has them designed, developed or manufactured, and markets them under its name or trademark.", "Manufacturers carry the central CRA duties for risk assessment, essential requirements, documentation, conformity and vulnerability handling.", law("Articles 3(13) and 13")),
  n("authorised_rep", "Authorised representative", "Authorised rep.", "actor", "roles", "A manufacturer may appoint an authorised representative by a written mandate.", "The representative performs the tasks specified in the mandate, subject to the limits in Article 18.", law("Articles 3 and 18")),
  n("importer", "Importer", "Importer", "actor", "roles", "An importer established in the Union places a product from a third country on the Union market.", "Before placing it on the market, the importer verifies specified conformity, documentation, information and marking duties.", law("Articles 3 and 19")),
  n("distributor", "Distributor", "Distributor", "actor", "roles", "A distributor makes a product available on the Union market but is not the manufacturer or importer.", "Distributors act with due care and verify specified marking, documentation and operator duties before making a product available.", law("Articles 3 and 20")),
  n("steward", "Open-source software steward", "OSS steward", "actor", "roles", "An open-source software steward systematically supports the development of qualifying free and open-source software intended for commercial activities.", "The definition excludes manufacturers and requires sustained support that ensures the viability of one or more products.", [r("law", "Articles 3(14) and 24"), r("guidance", "Section 3.2")]),
  n("notified_body", "Notified body", "Notified body", "actor", "roles", "A notified body is a conformity assessment body notified under the CRA.", "It can perform third-party conformity assessment where the selected or required procedure involves such a body.", law("Chapter IV")),
  n("market_authority", "Market surveillance authority", "Market authority", "actor", "roles", "Member State market surveillance authorities supervise products covered by the CRA.", "They can evaluate products and require corrective action where the Regulation's conditions are met.", law("Articles 52-58")),
  n("csirt", "Designated CSIRT", "CSIRT", "actor", "roles", "CRA reports are routed to the CSIRT designated as coordinator for the reporting Member State.", "The reporting architecture and information flow are set out in Articles 14-17.", law("Articles 14-17")),
  n("enisa", "ENISA", "ENISA", "actor", "roles", "ENISA has functions in the CRA reporting and Union-level coordination framework.", "The Regulation assigns ENISA tasks concerning the single reporting platform and information received under the reporting process.", law("Articles 14-17")),

  n("classification", "Product classification", "Classification", "process", "classification", "The CRA distinguishes products outside the important and critical lists, important products in Classes I and II, and critical products.", "Classification affects which conformity-assessment procedures can be used.", [r("law", "Articles 7-8, 32; Annexes III-IV"), r("faq", "Section 3")]),
  n("other_products", "Products outside special classes", "Other products", "concept", "classification", "Products not listed as important or critical use the general conformity-assessment rule in Article 32(1).", "Internal control can be used for these products, subject to the CRA conditions.", law("Article 32(1)")),
  n("important", "Important products with digital elements", "Important products", "concept", "classification", "Important products are divided into Class I and Class II and are listed by category in Annex III.", "The classes are subject to the conformity-assessment rules in Article 32.", law("Article 7 and Annex III")),
  n("class_i", "Important products - Class I", "Important Class I", "concept", "classification", "Annex III identifies Class I categories of important products with digital elements.", "Article 32 sets the assessment routes available for Class I products, including conditions tied to harmonised standards or common specifications.", law("Article 7, Article 32(2), Annex III Class I")),
  n("class_ii", "Important products - Class II", "Important Class II", "concept", "classification", "Annex III identifies Class II categories of important products with digital elements.", "Article 32 requires a third-party conformity-assessment route for Class II products.", law("Article 7, Article 32(3), Annex III Class II")),
  n("critical", "Critical products with digital elements", "Critical products", "concept", "classification", "Critical product categories are listed in Annex IV.", "Article 8 provides for European cybersecurity certification requirements for these categories under specified conditions.", law("Article 8 and Annex IV")),

  n("risk", "Cybersecurity risk assessment", "Risk assessment", "process", "security", "Manufacturers must assess cybersecurity risks and take the outcome into account across the product lifecycle described by the CRA.", "The CRA does not prescribe one specific assessment methodology. The assessment covers planning, design, development, production, delivery and maintenance.", [r("law", "Article 13(2)"), r("faq", "Questions 4.1.1-4.1.2")]),
  n("product_security", "Product cybersecurity requirements", "Product security", "obligation", "security", "Annex I Part I sets essential cybersecurity requirements for products with digital elements.", "The requirements are objective-oriented and technology-neutral; applicability and implementation are informed by the cybersecurity risk assessment.", [r("law", "Annex I, Part I"), r("faq", "Question 4.2.1")]),
  n("appropriate_security", "Appropriate level of cybersecurity", "Appropriate security", "obligation", "security", "Products must be designed, developed and produced to ensure an appropriate level of cybersecurity based on the risks.", "This is the opening product requirement in Annex I Part I.", law("Annex I, Part I, point 1")),
  n("secure_default", "Secure-by-default configuration", "Secure by default", "obligation", "security", "Where applicable, products must be made available with a secure-by-default configuration.", "Annex I also addresses resetting the product to its original state, subject to the stated conditions.", law("Annex I, Part I, point 2")),
  n("known_exploitable", "Known exploitable vulnerabilities", "Known exploitable", "concept", "security", "Where applicable, a product must be made available on the market without known exploitable vulnerabilities.", "The CRA does not require products to be free from every vulnerability; the requirement is risk-based and concerns known exploitable vulnerabilities.", [r("law", "Annex I, Part I, point 2(a)"), r("faq", "Question 4.2.2")]),
  n("access_control", "Protection from unauthorised access", "Access control", "obligation", "security", "Where applicable, products must protect against unauthorised access through appropriate control mechanisms.", "Annex I expressly includes authentication, identity and access management systems among the possible mechanisms.", law("Annex I, Part I, point 2")),
  n("confidentiality", "Confidentiality of data", "Confidentiality", "obligation", "security", "Where applicable, products must protect the confidentiality of stored, transmitted or otherwise processed data.", "Annex I includes encryption of relevant data at rest or in transit by state-of-the-art mechanisms among the means identified.", law("Annex I, Part I, point 2")),
  n("integrity", "Integrity of data and functions", "Integrity", "obligation", "security", "Where applicable, products must protect the integrity of stored, transmitted or otherwise processed data, commands, programs and configuration.", "The requirement includes protection against manipulation or modification not authorised by the user and reporting on corruptions.", law("Annex I, Part I, point 2")),
  n("data_minimisation", "Data minimisation", "Data minimisation", "obligation", "security", "Where applicable, products must process only data that are adequate, relevant and limited to what is necessary for the intended purpose.", "This requirement appears in Annex I Part I.", law("Annex I, Part I, point 2")),
  n("availability", "Availability of essential functions", "Availability", "obligation", "security", "Where applicable, products must protect the availability of essential and basic functions, including after an incident.", "Annex I gives resilience and mitigation measures against denial-of-service attacks as examples.", law("Annex I, Part I, point 2")),
  n("attack_surface", "Limited attack surfaces", "Attack surface", "obligation", "security", "Where applicable, products must be designed, developed and produced to limit attack surfaces, including external interfaces.", "This is one of the product cybersecurity requirements in Annex I Part I.", law("Annex I, Part I, point 2")),
  n("logging", "Security-relevant recording and monitoring", "Security logging", "obligation", "security", "Where applicable, products must provide security-related information by recording or monitoring relevant internal activity.", "The requirement includes an opt-out mechanism for users, subject to the Annex I wording.", law("Annex I, Part I, point 2")),

  n("vulnerability_handling", "Vulnerability-handling requirements", "Vulnerability handling", "obligation", "vulnerability", "Annex I Part II sets vulnerability-handling requirements that apply during the support period.", "They cover identification, documentation, remediation, testing, update distribution, disclosure policy and contact arrangements.", [r("law", "Annex I, Part II"), r("faq", "Question 4.1.3")]),
  n("support", "Support period", "Support period", "deadline", "vulnerability", "The support period must reflect expected use and listed factors and is at least five years unless expected use is shorter.", "During this period manufacturers must ensure vulnerabilities are handled effectively and in accordance with the essential requirements.", [r("law", "Article 13(8)"), r("faq", "Section 4.5")]),
  n("sbom", "Software bill of materials", "SBOM", "obligation", "vulnerability", "Manufacturers must identify and document vulnerabilities and components, including by drawing up a software bill of materials.", "The SBOM must use a commonly used machine-readable format and cover at least the product's top-level dependencies.", law("Annex I, Part II, point 1")),
  n("remediation", "Vulnerability remediation", "Remediation", "obligation", "vulnerability", "Manufacturers must address and remediate vulnerabilities without delay, including by providing security updates.", "Where technically feasible, new security updates must be provided separately from functionality updates.", law("Annex I, Part II, point 2")),
  n("testing", "Regular security testing and review", "Security testing", "process", "vulnerability", "Manufacturers must apply effective and regular tests and reviews of the security of the product.", "Commission guidance states that testing during the support period should be proportionate and updated when new input becomes available.", [r("law", "Annex I, Part II, point 3"), r("guidance", "Section 9.2.3")]),
  n("security_updates", "Security updates", "Security updates", "obligation", "vulnerability", "Security updates must be made available without delay and free of charge, except where the CRA permits a different agreement for a tailor-made product between a manufacturer and a business user.", "Manufacturers must provide users with information about security updates and the action required.", law("Article 13(8)-(9); Annex I, Part II")),
  n("update_availability", "Availability of security updates", "Update availability", "deadline", "vulnerability", "Security updates made available to users must remain available for the period required by Article 13(9).", "The period is at least ten years or the remainder of the support period, whichever is longer.", law("Article 13(9)")),
  n("secure_distribution", "Secure update distribution", "Secure distribution", "obligation", "vulnerability", "Manufacturers must distribute security updates securely and with mechanisms that address specified risks.", "Annex I includes automatic updates and clear opt-out arrangements where applicable.", law("Annex I, Part II")),
  n("cvd_policy", "Coordinated vulnerability disclosure policy", "CVD policy", "obligation", "vulnerability", "Manufacturers must put in place and enforce a policy on coordinated vulnerability disclosure.", "The policy is one of the vulnerability-handling requirements in Annex I Part II.", law("Annex I, Part II")),
  n("contact_point", "Vulnerability contact point", "Contact point", "obligation", "vulnerability", "Required user information includes a contact point where cybersecurity vulnerabilities can be reported.", "The contact information must allow the manufacturer to receive vulnerability reports.", law("Annex II")),
  n("components", "Third-party component due diligence", "Component diligence", "obligation", "vulnerability", "Manufacturers must exercise due diligence when integrating components sourced from third parties.", "They must ensure components do not compromise the cybersecurity of the product, including for qualifying free and open-source components.", [r("law", "Article 13(5)"), r("guidance", "Section 8.3")]),
  n("upstream", "Upstream vulnerability reporting", "Upstream reporting", "process", "vulnerability", "A manufacturer that identifies a vulnerability in an integrated component must report it to the person or entity maintaining that component.", "Article 13(6) also addresses sharing security fixes under specified conditions.", [r("law", "Article 13(6)"), r("guidance", "Section 9.2.1")]),

  n("reporting", "Mandatory CRA reporting", "Mandatory reporting", "process", "reporting", "Manufacturers must report actively exploited vulnerabilities and severe incidents affecting product security through the CRA reporting process.", "The reporting sequence is progressive: early warning, notification, then a final or complete report.", [r("law", "Article 14"), r("guidance", "Section 9.1")]),
  n("active_vulnerability", "Actively exploited vulnerability", "Exploited vulnerability", "concept", "reporting", "A vulnerability is actively exploited when there is reliable evidence that a malicious actor exploited it without the system owner's permission.", "The mandatory vulnerability reporting duty concerns actively exploited vulnerabilities, not every vulnerability.", [r("law", "Article 3(42)"), r("guidance", "Section 9.2.2")]),
  n("severe_incident", "Severe incident affecting product security", "Severe incident", "concept", "reporting", "Article 14 separately requires reporting of severe incidents having an impact on the security of a product with digital elements.", "The Regulation sets conditions for when such an incident is considered severe.", law("Article 14(3)-(4)")),
  n("warning_24", "Early warning", "Within 24 hours", "deadline", "reporting", "An early warning must be submitted without undue delay and, in any event, within 24 hours of awareness.", "This first-stage deadline applies to reportable actively exploited vulnerabilities and severe incidents.", [r("law", "Article 14(2)(a), (4)(a)"), r("guidance", "Section 9.1")]),
  n("notice_72", "Notification", "Within 72 hours", "deadline", "reporting", "A notification must follow without undue delay and, in any event, within 72 hours of awareness.", "It updates available information and includes an initial assessment as required by Article 14.", [r("law", "Article 14(2)(b), (4)(b)"), r("guidance", "Section 9.1")]),
  n("final_report", "Final or complete report", "Final report", "deadline", "reporting", "The final reporting stage follows the notification and uses the deadline specified for the type of reportable event.", "For an actively exploited vulnerability it is due within 14 days after a corrective or mitigating measure is available; for a severe incident the complete report is due within one month after notification.", [r("law", "Article 14(2)(c), (4)(c)"), r("guidance", "Section 9.1")]),
  n("user_information", "Information to affected users", "Inform users", "obligation", "reporting", "Where Article 14 applies, manufacturers must inform affected users about the event and, where necessary, measures they can take.", "The information duty and its coordination conditions are set out in Article 14.", law("Article 14(8)")),
  n("reporting_platform", "Single reporting platform", "Reporting platform", "process", "reporting", "The CRA provides for a single reporting platform for the reporting obligations in Article 14.", "Article 16 governs establishment and operation of the platform and the related information flow.", law("Article 16")),

  n("conformity", "Conformity assessment", "Conformity assessment", "process", "conformity", "Manufacturers must perform the applicable conformity-assessment procedure before placing a product on the market.", "The permitted route depends on product classification and, for Class I, full application of relevant harmonised standards, common specifications or certification schemes.", [r("law", "Article 32"), r("faq", "Section 6")]),
  n("internal_control", "Internal control", "Internal control", "process", "conformity", "Internal control is the conformity-assessment procedure in Annex VIII.", "Article 32 specifies when a manufacturer may use this procedure.", law("Article 32 and Annex VIII")),
  n("eu_type", "EU-type examination", "EU-type examination", "process", "conformity", "EU-type examination is the procedure in Annex IX.", "Where this route is used, it is followed by conformity to type based on internal production control in Annex X.", law("Article 32 and Annex IX")),
  n("conformity_type", "Conformity to type", "Conformity to type", "process", "conformity", "Conformity to type based on internal production control is set out in Annex X.", "It is paired with EU-type examination in the relevant Article 32 routes.", law("Article 32 and Annex X")),
  n("full_quality", "Full quality assurance", "Full quality assurance", "process", "conformity", "Full quality assurance is the conformity-assessment procedure in Annex XI.", "Article 32 identifies it as one of the available third-party routes.", law("Article 32 and Annex XI")),
  n("harmonised", "Harmonised standards", "Harmonised standards", "concept", "conformity", "Using harmonised standards is voluntary, but cited standards can provide a presumption of conformity for the requirements they cover.", "Manufacturers may use other technical solutions, but must demonstrate that the applicable CRA requirements are met.", [r("law", "Article 27"), r("faq", "Question 4.2.1")]),
  n("common_specs", "Common specifications", "Common specs", "concept", "conformity", "The Commission may establish common specifications by implementing acts under the conditions in Article 28.", "Products conforming to applicable common specifications benefit from the presumption described by the Regulation.", law("Article 28")),
  n("cyber_certification", "European cybersecurity certification", "EU certification", "concept", "conformity", "The CRA recognises specified European cybersecurity certification schemes in its conformity framework.", "Certification can support presumption of conformity and is also relevant to critical products under Article 8.", law("Articles 8 and 27")),
  n("documentation", "Technical documentation", "Technical documentation", "obligation", "conformity", "Manufacturers must draw up technical documentation before placing a product on the market and keep it up to date.", "Annex VII lists its content, including the cybersecurity risk assessment and means used to meet applicable essential requirements.", [r("law", "Article 13(12) and Annex VII"), r("faq", "Question 4.2.1")]),
  n("user_instructions", "Information and instructions to users", "User instructions", "obligation", "conformity", "Products must be accompanied by the information and instructions set out in Annex II.", "The required information covers the product, manufacturer, intended purpose, support period and security-relevant user information.", law("Article 13 and Annex II")),
  n("declaration", "EU declaration of conformity", "EU declaration", "obligation", "conformity", "The EU declaration states that fulfilment of the applicable essential cybersecurity requirements has been demonstrated.", "It follows the model structure in Annex V and must be kept up to date.", law("Article 29 and Annex V")),
  n("ce", "CE marking", "CE marking", "process", "conformity", "CE marking is affixed before a product with digital elements is placed on the market.", "The marking is subject to the general principles and affixing rules in Articles 30 and 31.", law("Articles 30-31")),

  n("substantial_modification", "Substantial modification", "Substantial change", "concept", "market", "A substantial modification is a post-market change that affects compliance or changes the intended purpose assessed by the manufacturer.", "A person carrying out a substantial modification can be subject to manufacturer obligations for the modified product.", [r("law", "Articles 3 and 22"), r("guidance", "Section 4")]),
  n("spare_parts", "Spare parts", "Spare parts", "concept", "market", "Commission guidance explains the CRA treatment of spare parts used to replace identical components in products.", "The assessment depends on the conditions described in the guidance, including the original manufacturer's specifications.", [r("guidance", "Section 4.2")]),
  n("corrective_action", "Corrective measures", "Corrective measures", "process", "market", "An economic operator that has reason to consider a product non-compliant must take the corrective measures required by the CRA.", "Depending on the circumstances, measures can include bringing the product into conformity, withdrawing it or recalling it.", law("Articles 13, 19-20 and 54")),
  n("withdrawal", "Withdrawal and recall", "Withdraw or recall", "process", "market", "The CRA uses withdrawal and recall as possible measures for products that do not meet applicable requirements.", "The applicable economic operator and market surveillance provisions determine when these measures are required.", law("Articles 13, 19-20 and 54")),
  n("market_surveillance", "Market surveillance", "Market surveillance", "process", "market", "The CRA establishes market-surveillance procedures for products with digital elements.", "Authorities evaluate products and coordinate action for non-compliance and significant cybersecurity risks.", law("Chapter V")),
  n("compliance_sweep", "Simultaneous coordinated control actions", "Compliance sweep", "process", "market", "The Commission may organise simultaneous coordinated control actions by market surveillance authorities for particular products or categories.", "Article 61 describes these actions, commonly referred to as sweeps.", law("Article 61")),
  n("penalties", "Penalties", "Penalties", "concept", "market", "Member States must lay down penalties for infringements of the CRA and take measures necessary to ensure implementation.", "Article 64 sets requirements and maximum administrative fine levels for specified infringements.", law("Article 64")),

  n("entry_force", "Entry into force", "10 Dec 2024", "deadline", "timeline", "The CRA entered into force on 10 December 2024.", "Article 71 provides that the Regulation enters into force on the twentieth day after publication in the Official Journal.", law("Article 71")),
  n("notified_date", "Notified-body provisions apply", "11 Jun 2026", "deadline", "timeline", "The CRA provisions in Chapter IV apply from 11 June 2026.", "This is an earlier application date specified in Article 71.", law("Article 71(2)")),
  n("reporting_date", "Reporting obligations apply", "11 Sep 2026", "deadline", "timeline", "The CRA reporting obligations apply from 11 September 2026.", "Commission guidance states that reporting is not retroactive to active exploitation already known before that date.", [r("law", "Article 71(2)"), r("guidance", "Section 9.1")]),
  n("application_date", "General application", "11 Dec 2027", "deadline", "timeline", "Most CRA provisions apply from 11 December 2027.", "Article 71 provides earlier dates for specified provisions, including reporting and notified-body rules.", law("Article 71")),
];

export const craLearningEdges: CraLearningEdge[] = [
  e("cra", "pde", "regulates", "Article 1"), e("cra", "economic_operator", "assigns duties to", "Chapter II"), e("cra", "classification", "classifies products through", "Articles 7-8"), e("cra", "product_security", "requires", "Annex I, Part I"), e("cra", "vulnerability_handling", "requires", "Annex I, Part II"), e("cra", "reporting", "requires", "Article 14"), e("cra", "conformity", "requires", "Article 32"), e("cra", "market_surveillance", "establishes", "Chapter V"), e("cra", "entry_force", "entered into force on", "Article 71"), e("cra", "application_date", "generally applies from", "Article 71"),
  e("pde", "software", "can be", "Article 3(1)"), e("pde", "hardware", "can be", "Article 3(1)"), e("pde", "component", "includes separately supplied", "Article 3(1)"), e("pde", "remote_processing", "can include", "Article 3(1)-(2)"), e("pde", "data_connection", "has", "Article 2(1)"), e("pde", "intended_use", "is assessed by", "Articles 2-3"), e("pde", "sector_exclusions", "is limited by", "Article 2"), e("making_available", "commercial_activity", "occurs in", "Article 3"), e("placing_market", "making_available", "is the first", "Article 3"), e("pde", "placing_market", "is subject to duties before", "Article 13"), e("software", "foss", "may qualify as", "Articles 2 and 3(48)"), e("foss", "commercial_activity", "is assessed against", "Article 2(1)"),
  e("economic_operator", "manufacturer", "includes", "Article 3"), e("economic_operator", "authorised_rep", "includes", "Article 3"), e("economic_operator", "importer", "includes", "Article 3"), e("economic_operator", "distributor", "includes", "Article 3"), e("foss", "steward", "may be supported by", "Article 3(14)"), e("manufacturer", "authorised_rep", "may appoint", "Article 18"), e("conformity", "notified_body", "may involve", "Chapter IV"), e("market_surveillance", "market_authority", "is performed by", "Chapter V"), e("reporting", "csirt", "is submitted to", "Article 14"), e("reporting_platform", "enisa", "is operated with tasks for", "Article 16"),
  e("classification", "other_products", "includes", "Article 32(1)"), e("classification", "important", "includes", "Article 7"), e("important", "class_i", "is divided into", "Article 7; Annex III"), e("important", "class_ii", "is divided into", "Article 7; Annex III"), e("classification", "critical", "includes", "Article 8; Annex IV"), e("other_products", "internal_control", "can use", "Article 32(1)"), e("class_i", "conformity", "determines routes for", "Article 32(2)"), e("class_ii", "conformity", "requires third-party routes under", "Article 32(3)"), e("critical", "cyber_certification", "may require", "Article 8"),
  e("manufacturer", "risk", "must perform", "Article 13(2)"), e("risk", "product_security", "informs application of", "Article 13(2); Annex I Part I"), e("product_security", "appropriate_security", "starts with", "Annex I, Part I, point 1"), e("product_security", "secure_default", "includes where applicable", "Annex I, Part I, point 2"), e("product_security", "known_exploitable", "includes where applicable", "Annex I, Part I, point 2(a)"), e("product_security", "access_control", "includes where applicable", "Annex I, Part I, point 2"), e("product_security", "confidentiality", "includes where applicable", "Annex I, Part I, point 2"), e("product_security", "integrity", "includes where applicable", "Annex I, Part I, point 2"), e("product_security", "data_minimisation", "includes where applicable", "Annex I, Part I, point 2"), e("product_security", "availability", "includes where applicable", "Annex I, Part I, point 2"), e("product_security", "attack_surface", "includes where applicable", "Annex I, Part I, point 2"), e("product_security", "logging", "includes where applicable", "Annex I, Part I, point 2"),
  e("manufacturer", "vulnerability_handling", "must fulfil", "Article 13(3)"), e("vulnerability_handling", "support", "applies during", "Article 13(8)"), e("vulnerability_handling", "sbom", "includes", "Annex I, Part II, point 1"), e("vulnerability_handling", "remediation", "includes", "Annex I, Part II, point 2"), e("vulnerability_handling", "testing", "includes", "Annex I, Part II, point 3"), e("remediation", "security_updates", "is performed through", "Annex I, Part II"), e("security_updates", "update_availability", "remain available for", "Article 13(9)"), e("security_updates", "secure_distribution", "must use", "Annex I, Part II"), e("vulnerability_handling", "cvd_policy", "includes", "Annex I, Part II"), e("cvd_policy", "contact_point", "is supported by", "Annex II"), e("manufacturer", "components", "must exercise", "Article 13(5)"), e("components", "upstream", "triggers when a vulnerability is found", "Article 13(6)"),
  e("manufacturer", "reporting", "must perform", "Article 14"), e("reporting", "active_vulnerability", "covers", "Article 14(1)-(2)"), e("reporting", "severe_incident", "covers", "Article 14(3)-(4)"), e("reporting", "warning_24", "starts with", "Article 14(2)(a), (4)(a)"), e("warning_24", "notice_72", "is followed by", "Article 14(2)(b), (4)(b)"), e("notice_72", "final_report", "is followed by", "Article 14(2)(c), (4)(c)"), e("reporting", "user_information", "also requires", "Article 14(8)"), e("reporting", "reporting_platform", "uses", "Article 16"), e("reporting", "reporting_date", "applies from", "Article 71(2)"),
  e("classification", "conformity", "determines routes for", "Article 32"), e("conformity", "internal_control", "can use", "Article 32; Annex VIII"), e("conformity", "eu_type", "can use", "Article 32; Annex IX"), e("eu_type", "conformity_type", "is followed by", "Article 32; Annex X"), e("conformity", "full_quality", "can use", "Article 32; Annex XI"), e("harmonised", "conformity", "supports presumption in", "Article 27"), e("common_specs", "conformity", "supports presumption in", "Article 28"), e("cyber_certification", "conformity", "can support", "Article 27"), e("manufacturer", "documentation", "must draw up", "Article 13(12); Annex VII"), e("manufacturer", "user_instructions", "must provide", "Article 13; Annex II"), e("conformity", "declaration", "leads to", "Article 29"), e("declaration", "ce", "precedes", "Articles 29-31"), e("ce", "placing_market", "is affixed before", "Article 31"),
  e("substantial_modification", "manufacturer", "can create obligations of", "Article 22"), e("component", "spare_parts", "can be supplied as", "Guidance Section 4.2", "guidance"), e("economic_operator", "corrective_action", "must take when required", "Articles 13, 19-20"), e("corrective_action", "withdrawal", "can include", "Article 54"), e("market_surveillance", "corrective_action", "can require", "Article 54"), e("market_surveillance", "compliance_sweep", "can include", "Article 61"), e("market_surveillance", "penalties", "is reinforced by", "Article 64"),
  e("entry_force", "notified_date", "is followed by", "Article 71"), e("notified_date", "reporting_date", "is followed by", "Article 71"), e("reporting_date", "application_date", "is followed by", "Article 71"),
];

export const craLearningPaths = [
  { id: "start", title: "Understand the CRA", description: "Scope, actors and the product lifecycle.", nodes: ["cra", "pde", "placing_market", "manufacturer", "risk", "product_security", "vulnerability_handling", "conformity", "market_surveillance"] },
  { id: "scope", title: "Is a product in scope?", description: "Trace products, connections, software and exclusions.", nodes: ["pde", "software", "component", "remote_processing", "data_connection", "intended_use", "foss", "commercial_activity", "sector_exclusions"] },
  { id: "security", title: "Build a secure product", description: "Follow risk into the essential product requirements.", nodes: ["risk", "product_security", "appropriate_security", "secure_default", "known_exploitable", "access_control", "confidentiality", "integrity", "availability", "attack_surface"] },
  { id: "vulnerability", title: "Handle vulnerabilities", description: "From component diligence to supported updates.", nodes: ["components", "upstream", "vulnerability_handling", "sbom", "testing", "remediation", "security_updates", "secure_distribution", "support"] },
  { id: "incident", title: "Report security events", description: "Follow the progressive CRA reporting sequence.", nodes: ["reporting", "active_vulnerability", "severe_incident", "warning_24", "notice_72", "final_report", "user_information", "reporting_platform", "reporting_date"] },
  { id: "market", title: "Reach the Union market", description: "Classify, assess, document and mark the product.", nodes: ["classification", "important", "conformity", "harmonised", "documentation", "user_instructions", "declaration", "ce", "placing_market"] },
  { id: "oversight", title: "After market placement", description: "Changes, corrective action and public oversight.", nodes: ["substantial_modification", "manufacturer", "corrective_action", "withdrawal", "market_surveillance", "compliance_sweep", "penalties"] },
  { id: "dates", title: "CRA application timeline", description: "The four central application milestones.", nodes: ["entry_force", "notified_date", "reporting_date", "application_date"] },
] as const;

export function validateCraLearningGraph(): string[] {
  const errors: string[] = [];
  const nodeIds = new Set<string>();
  const topics = new Set(craTopics.filter(topic => topic.id !== "all").map(topic => topic.id));
  const sourceIds = new Set(Object.keys(craSources));
  for (const node of craLearningNodes) {
    if (nodeIds.has(node.id)) errors.push(`Duplicate node: ${node.id}`);
    nodeIds.add(node.id);
    if (!topics.has(node.topic)) errors.push(`Unknown topic: ${node.id}/${node.topic}`);
    if (!node.references.length) errors.push(`Missing source: ${node.id}`);
    for (const source of node.references) if (!sourceIds.has(source.sourceId)) errors.push(`Unknown source on ${node.id}: ${source.sourceId}`);
  }
  const connected = new Set<string>();
  for (const edge of craLearningEdges) {
    if (!nodeIds.has(edge.from) || !nodeIds.has(edge.to)) errors.push(`Invalid edge: ${edge.from} -> ${edge.to}`);
    else { connected.add(edge.from); connected.add(edge.to); }
    if (!edge.label.trim()) errors.push(`Missing relation: ${edge.from} -> ${edge.to}`);
    if (!edge.references.length) errors.push(`Missing edge source: ${edge.from} -> ${edge.to}`);
  }
  for (const id of nodeIds) if (!connected.has(id)) errors.push(`Orphan node: ${id}`);
  for (const path of craLearningPaths) for (const id of path.nodes) if (!nodeIds.has(id)) errors.push(`Invalid path node: ${path.id}/${id}`);
  return errors;
}
