from __future__ import annotations

# Verbatim Annex A question and response text, ENISA 2026, CC BY 4.0.
OFFICIAL_QUESTIONS = [{'code': '1.1',
  'question': 'Do you have written and approved product security policies?',
  'levels': {'1': 'No product security policies or guidelines exist.',
             '2': 'Some basic guidelines exist but are informal or incomplete.',
             '3': 'Documented policies or guidelines exist but are not formally approved or consistently used.',
             '4': 'Policies are formally approved, documented and generally applied.',
             '5': 'Policies are formally approved, consistently applied, regularly reviewed and continuously improved.'}},
 {'code': '1.2',
  'question': 'Are roles and responsibilities clearly defined for product security activities (e.g. development, vulnerability management, '
              'updates)?',
  'levels': {'1': 'No roles or responsibilities are defined.',
             '2': 'Responsibilities exist informally but are unclear or inconsistently assigned.',
             '3': 'Responsibilities are documented but not consistently applied in practice.',
             '4': 'Responsibilities are clearly defined, documented and consistently applied.',
             '5': 'Responsibilities are clearly defined, communicated, consistently applied, regularly reviewed and continuously '
                  'improved.'}},
 {'code': '1.3',
  'question': 'Do you maintain product-level technical documentation describing implemented security features, risk assessments, design '
              'decisions and update procedures?',
  'levels': {'1': 'No product security documentation exists.',
             '2': 'Limited or incomplete documentation exists covering only some aspects.',
             '3': 'Documentation covering most required aspects exists but is incomplete or not consistently maintained.',
             '4': 'Documentation is complete for most products and consistently maintained.',
             '5': 'Documentation is complete for all products and is formally maintained, regularly reviewed and continuously improved.'}},
 {'code': '1.4',
  'question': 'Is there a process to regularly review product security and the quality of related documentation?',
  'levels': {'1': 'No review process exists.',
             '2': 'Reviews happen informally or occasionally.',
             '3': 'A documented review process exists but is not consistently applied.',
             '4': 'Reviews are consistently performed and documented.',
             '5': 'Reviews are measured, tracked and continuously improved.'}},
 {'code': '1.5',
  'question': 'Are you aware of the market surveillance authority responsible for enforcing the CRA, the conformity assessment procedure '
              'applicable to your products, and how to interact with relevant authorities if needed?',
  'levels': {'1': 'No awareness of authorities or obligations.',
             '2': 'Limited awareness but no clear understanding of obligations.',
             '3': 'Authorities and obligations are known but not formally documented.',
             '4': 'Authorities, obligations and interaction processes are defined and followed.',
             '5': 'Awareness and interaction processes are formalised, maintained and regularly reviewed.'}},
 {'code': '2.1',
  'question': 'Do you perform cybersecurity risk assessments and use the results to guide product design, development, configuration and '
              'component management decisions?',
  'levels': {'1': 'No risk assessments are performed.',
             '2': 'Risk assessments are informal and rarely influence decisions.',
             '3': 'Risk assessments are documented but not consistently used.',
             '4': 'Risk assessments are systematically performed and guide decisions.',
             '5': 'Risk assessments are formalised, integrated into processes and continuously improved.'}},
 {'code': '2.2',
  'question': 'Are products designed using security by design principles from the outset?',
  'levels': {'1': 'Security by design is not considered.',
             '2': 'Security by design is considered occasionally or late in development.',
             '3': 'Security by design is applied during design but not consistently.',
             '4': 'Security by design is consistently applied across products and regularly reviewed.',
             '5': 'Security by design is fully integrated into development and continuously improved.'}},
 {'code': '2.3',
  'question': 'Are products delivered with secure by default configurations and settings?',
  'levels': {'1': 'No secure defaults are defined.',
             '2': 'Secure defaults exist but are inconsistent.',
             '3': 'Secure defaults are defined but not consistently applied.',
             '4': 'Secure defaults are consistently applied and reviewed.',
             '5': 'Secure defaults are enforced, tested and continuously improved.'}},
 {'code': '2.4',
  'question': 'Do you perform security checks and testing before releasing or updating a product, and to what extent are automated tools '
              'used?',
  'levels': {'1': 'No security testing is performed.',
             '2': 'Testing is occasional and mostly manual.',
             '3': 'Testing is documented and includes some automated tools.',
             '4': 'Testing is systematically integrated into development workflows and regularly reviewed.',
             '5': 'Testing is risk based, automated where appropriate, monitored and continuously improved.'}},
 {'code': '2.5',
  'question': 'When risks change or new threats emerge, are risk assessments, configurations and third-party components reviewed and '
              'updated?',
  'levels': {'1': 'No structured review or update process exists.',
             '2': 'Updates are informal or occasional.',
             '3': 'Reviews are documented but not consistently applied.',
             '4': 'Reviews and updates are consistently performed across products.',
             '5': 'Continuous monitoring and structured updates are in place and continuously improved.'}},
 {'code': '3.1',
  'question': 'Do you have a process to receive, acknowledge, record and track vulnerabilities reported by customers, researchers or '
              'internal staff?',
  'levels': {'1': 'No vulnerability tracking exists.',
             '2': 'Vulnerabilities are handled informally.',
             '3': 'A documented tracking process exists but is not consistently applied.',
             '4': 'Vulnerabilities are consistently tracked and reviewed.',
             '5': 'Tracking is measured, integrated and continuously improved.'}},
 {'code': '3.2',
  'question': 'Do you have a defined process for creating, testing and delivering security updates for supported products and '
              'communicating them to customers?',
  'levels': {'1': 'No update process exists.',
             '2': 'Updates are handled informally.',
             '3': 'A documented process exists but is not consistently followed.',
             '4': 'Updates are consistently managed, tested and delivered.',
             '5': 'The process is monitored, measured and continuously improved.'}},
 {'code': '3.3',
  'question': 'Do you maintain and use SBOMs to support vulnerability and dependency management?',
  'levels': {'1': 'No SBOMs are created or maintained.',
             '2': 'SBOMs are created occasionally or manually.',
             '3': 'SBOMs are documented for most products but not consistently maintained or used.',
             '4': 'SBOMs are systematically maintained and used in vulnerability management.',
             '5': 'SBOMs are integrated, automated where appropriate and continuously improved.'}},
 {'code': '3.4',
  'question': 'Are vulnerabilities and updates prioritised based on risk and potential impact?',
  'levels': {'1': 'No prioritisation is performed.',
             '2': 'Prioritisation is informal.',
             '3': 'A documented prioritisation approach exists but is not consistently applied.',
             '4': 'Prioritisation is consistently risk based and applied.',
             '5': 'Prioritisation is measured, reviewed and continuously improved.'}},
 {'code': '3.5',
  'question': 'Do you verify that security updates resolve reported vulnerabilities effectively and maintain evidence of this '
              'verification?',
  'levels': {'1': 'No verification is performed.',
             '2': 'Verification is informal or occasional.',
             '3': 'Verification is documented but not consistently applied.',
             '4': 'Verification is consistently performed and documented.',
             '5': 'Verification is measured, reviewed and continuously improved.'}},
 {'code': '4.1',
  'question': 'Is there a defined approach to managing product security during the operational phase?',
  'levels': {'1': 'No structured approach exists.',
             '2': 'Some practices exist but are informal.',
             '3': 'A documented approach exists but is not consistently applied.',
             '4': 'The approach is consistently applied and reviewed.',
             '5': 'The approach is monitored, measured and continuously improved.'}},
 {'code': '4.2',
  'question': 'Is the product life cycle management actively managed, including defined support periods, update responsibilities, '
              'end-of-life arrangements and communication with customers?',
  'levels': {'1': 'No life-cycle management exists.',
             '2': 'Life-cycle activities are informal.',
             '3': 'Life-cycle processes are documented but not consistently applied.',
             '4': 'Life-cycle management is consistently applied and communicated.',
             '5': 'Life-cycle management is monitored, reviewed and continuously improved.'}},
 {'code': '4.3',
  'question': 'Is experience from product operation, post-incident reviews and customer input used to improve products over time?',
  'levels': {'1': 'No structured improvement process exists.',
             '2': 'Improvements are implemented occasionally and informally.',
             '3': 'A documented improvement approach exists but is not consistently applied.',
             '4': 'Improvements are consistently implemented and tracked.',
             '5': 'Continuous improvement is measured and integrated into product management.'}},
 {'code': '4.4',
  'question': 'Is there a structured and tested way to address identified product security issues?',
  'levels': {'1': 'No defined method exists.',
             '2': 'Issues are handled inconsistently.',
             '3': 'A documented method exists but is not consistently applied or tested.',
             '4': 'Issues are handled through a consistent and reviewed process.',
             '5': 'The process is tested, measured and continuously improved.'}},
 {'code': '4.5',
  'question': 'Are products monitored during operation to identify security risks, vulnerabilities and emerging threats?',
  'levels': {'1': 'No monitoring exists.',
             '2': 'Monitoring is informal or occasional.',
             '3': 'Monitoring is documented but not consistently applied.',
             '4': 'Monitoring is consistently performed and results are tracked.',
             '5': 'Monitoring is integrated, risk based and continuously improved.'}},
 {'code': '5.1',
  'question': 'Are sufficient skills available to design, develop and maintain products in a secure way, including through external '
              'expertise where internal capacity is limited?',
  'levels': {'1': 'No relevant expertise is available.',
             '2': 'Limited expertise is available and applied informally.',
             '3': 'Skills are documented but not consistently sufficient.',
             '4': 'Skills are sufficient, applied and regularly reviewed.',
             '5': 'Skills are assessed, developed and continuously improved.'}},
 {'code': '5.2',
  'question': 'Do staff receive appropriate training on cybersecurity practices relevant to their roles, including product risk '
              'management, vulnerability management, and security by design?',
  'levels': {'1': 'No training is provided.',
             '2': 'Training is informal or occasional.',
             '3': 'Training is documented but not consistently delivered.',
             '4': 'Training is regularly delivered and reviewed.',
             '5': 'Training effectiveness is assessed and continuously improved.'}},
 {'code': '5.3',
  'question': 'Does the organisation promote a culture of responsible product development, open reporting and awareness of product risks?',
  'levels': {'1': 'No promotion of responsible product development or product risk awareness.',
             '2': 'Responsible practices and product risks are discussed informally.',
             '3': 'Expectations are documented but not consistently applied.',
             '4': 'Responsible practices are consistently encouraged and applied.',
             '5': 'Culture is embedded, measured and continuously improved.'}},
 {'code': '5.4',
  'question': 'Do you follow relevant external product security information (e.g. advisories, alerts)?',
  'levels': {'1': 'No external information is followed.',
             '2': 'Information is followed occasionally.',
             '3': 'Sources are documented but not consistently used.',
             '4': 'Information is consistently monitored and used.',
             '5': 'Engagement is active, integrated and continuously improved.'}},
 {'code': '5.5',
  'question': 'Do you assess your team and validate that it has the required skills and competence to maintain secure products?',
  'levels': {'1': 'No assessment exists.',
             '2': 'Assessment is informal.',
             '3': 'Assessment is documented but not consistently applied.',
             '4': 'Assessment is consistently performed and gaps are addressed.',
             '5': 'Competence is measured, tracked and continuously improved.'}}]
